apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: game-api-test-deployment 
  namespace: tg
  labels: 
    app: game-api-test
    environment: dev
    aadpodidbinding: eastus2-dev-tg-azure-identity
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: game-api-test
  template: 
    metadata: 
      labels: 
        app: game-api-test
        environment: dev
        aadpodidbinding: eastus2-dev-tg-azure-identity
    spec:
      nodeSelector:
        pool: services
      tolerations:
        - key: "ServicesOnly"
          operator: "Exists"
          effect: "NoSchedule"
      containers: 
      - name: game-api-test
        image: eastus2tgacr.azurecr.io/game-api:25
        env: 
          - name: ASPNETCORE_ENVIRONMENT  
            value: 'Development'
          - name: SERVICE_NAME  
            value: 'game-api-test'
        ports: 
        - containerPort: 80
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 25
        #   periodSeconds: 10
        #   timeoutSeconds: 5