apiVersion: v1
kind: ServiceAccount
metadata:
  name: ##SERVICE_ACCOUNT##
  namespace: ##SERVICE_NAMESPACE##
  labels: 
    environment: ##ENVIRONMENT##
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ##SERVICE_ACCOUNT##-role
  namespace: ##SERVICE_NAMESPACE##
  labels: 
    environment: ##ENVIRONMENT##
rules:
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - endpoints
  - deployments
  - services
  - pods
  - pods/log
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ##SERVICE_ACCOUNT##-role-binding
  namespace: ##SERVICE_NAMESPACE##
  labels: 
    environment: ##ENVIRONMENT##
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ##SERVICE_ACCOUNT##-role
subjects:
- kind: ServiceAccount
  name: ##SERVICE_ACCOUNT##
  namespace: ##SERVICE_NAMESPACE##
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ##SERVICE_ACCOUNT##-cluster-role
  labels: 
    environment: ##ENVIRONMENT##
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - nodes
  verbs:
  - list
  - get
---  
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ##SERVICE_ACCOUNT##-cluster-role-binding
  namespace: ##SERVICE_NAMESPACE##
  labels: 
    environment: ##ENVIRONMENT##
subjects:
- kind: ServiceAccount
  name: ##SERVICE_ACCOUNT##
  namespace: ##SERVICE_NAMESPACE##
roleRef:
  kind: ClusterRole
  name: ##SERVICE_ACCOUNT##-cluster-role
  apiGroup: rbac.authorization.k8s.io